name: Run Container Destroy

on:
  workflow_dispatch:

jobs:
  deploy_container:
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.TOKEN }}
        repository: CJN-Team/pet-project-services
        event-type: destroy-container
        client-payload: '{"app_name": "${{ vars.APP_NAME }}"}} }'
