name: Run Container Destroy

on:
  workflow_dispatch:

jobs:
  deploy_container:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Read JSONs
      id: set_var
      run: |
        echo "SWAGGER=$(jq -c . < ./Pet.Project.Profile.Api/OpenAPI/ProfileSwagger.json)" >> $GITHUB_ENV

    - name: Set environment specific variables
      uses: jnus/json-variables@v1.0
      with:
        scope: deploy
        configFile: './Variables/Actions.json'
        secrets: '${{ toJson(secrets) }}'

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.TOKEN }}
        repository: ${{ env.REPOSITORY }}
        event-type: destroy-container
        client-payload: '{"app_name": "${{ env.APP_NAME }}", "containers": ${{ toJson(vars.CONTAINERS) }}, "app_name_api": "${{ env.APP_NAME_API }}", "app_name_display_name": "${{ env.APP_NAME_DISPLAY_NAME }}", "app_description": "${{ env.APP_DESCRIPTION }}", "app_path": "${{ env.APP_PATH }}", "content": ${{ toJson(env.SWAGGER) }} }'
